#!/bin/sh

set -e

# update grub on first install, so that the alternative init system boot
# entries get updated
if [ "$1" = configure ] && [ -z "$2" ] && [ -e /boot/grub/grub.cfg ] && command -v update-grub >/dev/null; then
    update-grub || true
fi

# Pexip specific migration from upstart
# file removed in commit 0244ae33b21f71966de0c58bc7de35faad58000c
# Can be removed after v35 gatepost release
if [ "$1" = configure ]; then
    rm -f /etc/init/rc.conf
fi

#DEBHELPER#
